[package]
name = "b_crane_and_turtle"
version = "0.1.0"
authors = ["ir77 <fly.oh.shogun.iridium.77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
